# Generated by Django 4.0.6 on 2022-07-30 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('valute', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valute',
            options={'verbose_name': 'Валюта', 'verbose_name_plural': 'Валюта'},
        ),
        migrations.CreateModel(
            name='Tranzaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('valute', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='valute.valute')),
            ],
        ),
    ]
