# Generated by Django 4.0.6 on 2022-07-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_card', '0002_alter_scanedcard_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanedcard',
            name='created_at',
            field=models.IntegerField(default=20220730125536),
        ),
    ]
