# Generated by Django 4.0.6 on 2022-07-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_card', '0003_alter_scanedcard_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanedcard',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
