# Generated by Django 4.0.6 on 2022-07-04 17:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_party', models.IntegerField(verbose_name='Номер отряда')),
                ('name', models.CharField(max_length=255, verbose_name='Название отряда')),
                ('token_qr', models.CharField(default=uuid.UUID('a7cc132e-175e-4a95-ab77-4ffc3d4ac371'), max_length=255, verbose_name='Номер qr')),
                ('money', models.IntegerField(default=0, verbose_name='Деньги')),
            ],
        ),
    ]
