# Generated by Django 4.0.6 on 2022-07-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='party',
            options={'verbose_name': 'Отряд', 'verbose_name_plural': 'Отряд'},
        ),
        migrations.RemoveField(
            model_name='party',
            name='token_qr',
        ),
        migrations.AddField(
            model_name='party',
            name='card',
            field=models.IntegerField(default=1, verbose_name='Номер карточки'),
            preserve_default=False,
        ),
    ]
